name: Documentation

on:
    # Trigger the workflow on push or pull request,
    # but only for the main branch
   push:
     branches:
       - master
   pull_request:
     branches:
       - master

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout acse-1-assessment-3-acse-jrt3817
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme
        apt-get update -y
        apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
        pip install -e .

    - name: Generate documentation
      working-directory: docs
      run: |
        sphinx-build -b html . _build/html
        sphinx-build -b latex . _build/latex
        cd _build/latex
        pdflatex acse_la.tex

    - name: push changes to repo
      run: |
        git config --global user.email "jrt3817@ic.ac.uk"
        git config --global user.name "acse-jrt3817"
        git add docs
        git commit -m "Update documentation"
        git push